version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"

  mysql-adminer:
    image: adminer:latest
    container_name: my-sql-adminer
    ports:
      - "5050:8080"